### ISSUE TITLE
memRealloc on a filled-buffer throws Exception due to "no remaining elements"

### ISSUE THREAD

**Issue by Guerra24** [LWJGLX/debug#19]
```java
ByteBuffer buf = memAlloc(8);
int bytes = 0;
for (int i = 0; i < 64; ++i) {
	buf.put((byte) i);
	++bytes;
	if (i + 1 == bytes)
		buf = memRealloc(buf, bytes * 2);
}
for (int i = 0; i < 64; ++i) 
	System.out.println(buf.get(i));
memFree(buf);
```
The code above throws an `IllegalArgumentException` in the `memRealloc` call.
```java
Exception in thread "main" java.lang.IllegalArgumentException: buffer has no remaining elements. Did you forget to flip()/rewind() it?
```
Without the agent attached it works fine and to confirm I wrote the same code in C and had no issues.

LWJGL 3.2.1 and JDK 11

**Comment by httpdigest** [comment]
Thanks! This validation existed, because usually, it is an error in the user code to hand a non-flipped/no-remaining buffer to an API method, such as an OpenGL method. But for MemoryUtil.memRealloc/memFree this is of course not the case. A new build is underway and should be available in a few minutes.
